# Default/example values for a Rails application.

service:
  type: NodePort
  annotations: {}
  port: 80

ingress:
  enabled: false

# appEnabled determines whether the web app Deployment is created.
appEnabled: true
replicaCount: 2
podDisruptionBudget: {}

# redis.enabled controls whether a Redis database is set up for the app
# REDIS_URL is automatically set unless redis.redisUrlOverride values are provided
redis:
  enabled: false
  image:
    repository: redis
    tag: "7.4"
    pullPolicy: Always
  storageClassName: ebs-gp3
  storage: 10Gi
  resources:
    limits:
      cpu: 1
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  config:
    # Needs to be smaller that the memory limit with some buffer
    maxmemory: 1000mb
  redisUrlOverride:
    app: ""
    workers: ""

# dbMigrationEnabled controls whether Rails database migrations are run on install/upgrade.
dbMigrationEnabled: false
dbMigrationCommand: ["rails", "db:migrate"]

repoName: "example"  # Dummy value, overridden in ArgoCD config.
# arch determines whether the app should schedule on amd64 or arm64 nodes.
arch: amd64
appImage:
  repository: ""  # Dummy value, overridden in ArgoCD config.
  pullPolicy: Always
  tag: latest
appPort: 3000
# appExtraVolumeMounts defines VolumeMounts on the app container (in both
# deployment.yaml and worker-deployment.yaml).
appExtraVolumeMounts: []

# appProbes defines liveness/readiness/startup probes for the app container.
# See templates/deployment.yaml file for the default values.
# When overriding these probes, you must override all three probes if you need
# them - the whole block is replaced.
appProbes: {}

nginxImage:
  repository: public.ecr.aws/nginx/nginx
  pullPolicy: Always
  tag: stable
nginxPort: 8080
nginxProxyConnectTimeout: 2s
nginxProxyReadTimeout: 15s
nginxClientMaxBodySize: 1M
nginxConfigMap:
  create: true
nginxExtraVolumeMounts: []
nginxDenyCrawlers: false
proxyRailsAssetsToS3: true
serveRailsAssetsFromFilesystem: false

appResources:
  limits:
    cpu: 1
    memory: 1500Mi
  requests:
    cpu: 500m
    memory: 800Mi

nginxResources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 512Mi

# dnsConfig is passed directly into the pod specs in the app and worker
# deployment templates.
dnsConfig: {}

# extraEnv is a list of (name, value) pairs representing additional environment
# variables to pass to app containers. extraEnv is evaluated through `tpl`, so
# Helm values can be substituted using Go template syntax. Use sparingly.
extraEnv: {}
#  - name: RETICULATE_SPLINES
#    value: "true"
#  - name: SPLINE_SERVER
#    value: "https://splines.{{ .Values.externalDomain }}"

publishingPlatformEnvironment: test
uploadAssets:
  enabled: true

metricsPort: 9394

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 1001
  runAsGroup: 1001
  readOnlyRootFilesystem: true

sentry:
  enabled: true
  createSecret: true

rails:
  enabled: true
  createKeyBaseSecret: true

externalSecrets:
  deletionPolicy: Delete
  refreshInterval: 1h  # Be kind to etcd and don't set this too short.
