{{- if and .Values.appEnabled .Values.podDisruptionBudget }}
{{- $fullName := include "generic-publishing-platform-app.fullname" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic-publishing-platform-app.labels" . | nindent 4 }}
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/component: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullName }}
      app.kubernetes.io/component: app
  {{- .Values.podDisruptionBudget | toYaml | nindent 2 }}
{{- end }}
