apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authenticating-proxy
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Secrets for Authenticating Proxy
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: authenticating-proxy
    template:
      mergePolicy: Merge
      engineVersion: v2    
      data:
        DATABASE_URL: '{{ $.Files.Get "externalsecrets-templates/psql-conn-string.tpl" | trim }}/authenticating_proxy_production'
  dataFrom:
    - extract:
        key: publishing-platform/authenticating-proxy
