apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: organisations-publisher
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Secrets for Organisations Publisher
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: organisations-publisher
    template:
      mergePolicy: Merge
      engineVersion: v2    
      data:
        DATABASE_URL: '{{ $.Files.Get "externalsecrets-templates/psql-conn-string.tpl" | trim }}/organisations_publisher_production'
  dataFrom:
    - extract:
        key: publishing-platform/organisations-publisher
