apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signon-postgres
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Credentials and connection details for Postgres hosted in RDS for Signon.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: signon-postgres
    template:
      data:
        DATABASE_URL: '{{ $.Files.Get "externalsecrets-templates/psql-conn-string.tpl" | trim }}/signon_production'
  dataFrom:
    - extract:
        key: publishing-platform/signon/postgres
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signon
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Secrets for Signon
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: active-record-encryption
  dataFrom:
    - extract:
        key: publishing-platform/signon
