# Default values for the app-config chart.
#
# Setting a value here will set it for all app charts in all environments,
# though values can still be overridden per-app and/or per-environment.
#
# See values-${env}.yaml for per-environment and per-app values.

awsRegion: eu-west-2

appsNamespace: apps
argoNamespace: cluster-services
monitoringNamespace: monitoring
workflowsNamespace: apps

publishingPlatformApplications: []
publishingPlatformEnvironment: test
ec2InternalDomainSuffix: publishing-platform-internal.top
k8sExternalDomainSuffix: eks.test.publishing-platform.top
externalDomainSuffix: test.publishing.service.publishing-platform.co.uk
publishingDomainSuffix: test.publishing.service.publishing-platform.co.uk

cspReportURI: ""

monitoring:
  enabled: true
  authorisation:
    githubOrganisation: publishing-platform
    readOnlyGithubTeam: publishing-platform
    readWriteGithubTeam: publishing-platform-production-admin
