apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: {{ .Values.argoNamespace | default .Release.Namespace }}
spec:
  project: default
  source:
    {{- include "app-config.helm-release"
        ( merge (deepCopy .) (dict "repoURL" "https://kubernetes.github.io/autoscaler" "chart" "cluster-autoscaler") )
        | nindent 4 }}
    helm:
      values: |
        awsRegion: {{ .Values.awsRegion }}
        rbac:
          create: true
          serviceAccount:
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountId }}:role/cluster-autoscaler-publishing-platform
        autoDiscovery:
          clusterName: publishing-platform
          enabled: true
        extraArgs:
          balance-similar-node-groups: true
          scale-down-utilization-threshold: "0.55"
          skip-nodes-with-local-storage: false
          v: "0"
        replicaCount: {{ .Values.replicaCount }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
