apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: {{ .Values.argoNamespace | default .Release.Namespace }}
spec:
  project: default
  source:
    {{- include "app-config.helm-release"
        ( merge (deepCopy .) (dict "repoURL" "https://kubernetes-sigs.github.io/external-dns" "chart" "external-dns") )
        | nindent 4 }}
    helm:
      values: |
        provider: aws
        env:
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.awsRegion }}
        extraArgs:
          - --aws-zone-type=public
        serviceAccount:
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountId }}:role/external-dns-publishing-platform
        automountServiceAccountToken: true
        revisionHistoryLimit: 10
        txtOwnerId: publishing-platform
        domainFilters:
          - {{ .Values.k8sExternalDomainSuffix }}
        interval: 5m
        triggerLoopOnEvent: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argoNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
