externalDomainSuffix: test.publishing.service.publishing-platform.co.uk
publishingDomainSuffix: test.publishing.service.publishing-platform.co.uk

publishingPlatformEnvironment: test

arch: amd64

appResources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 1Gi

externalSecrets:
  refreshInterval: 1h  # Be kind to etcd and don't set this too short.
  deletionPolicy: Delete
