apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: publishing-platform-ci-github-creds
  namespace: {{ .Values.workflowsNamespace }}
  annotations:
    kubernetes.io/description: >
       Personal access token for publishing-platform-ci GitHub user
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: publishing-platform-ci-github-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: publishing-platform/github/publishing-platform-ci
