apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: publishing-platform-dex-github
  namespace: {{ .Values.clusterServicesNamespace }}
  annotations:
    kubernetes.io/description: >
      This secret is used to allow Dex (https://dexidp.io/), a federated
      OpenID connect provider, to use GitHub as an identity provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: publishing-platform-dex-github
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: publishing-platform/dex/github
