apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: publishing-platform-dex-argo-workflows
  namespace: "{{ .Values.clusterServicesNamespace }}"
  annotations:
    kubernetes.io/description: >
      This secret contains the OAUTH secret which allows Argo-Workflows to
      authenticate with Dex (https://dexidp.io/), a federated
      OpenID connect provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: publishing-platform-dex-argo-workflows
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: publishing-platform/dex/argo-workflows
