apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": [
        "publishing-platform/publishing-platform-helm-charts",
        "publishing-platform/publishing-platform-infrastructure"
      ]
    }
